# -*- coding: utf-8 -*-
"""mikolaj_n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUF7jt49Ose1o-oEoJrfnsYZQru0qq_9
"""

import streamlit as st
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle, Polygon, Ellipse

## 🧑‍🎄 Kod Streamlit: Rysunek Mikołaja
---

# Tytuł aplikacji
st.title("🎅 Rysunek Mikołaja za pomocą Matplotlib")
st.write("Ten kod generuje Mikołaja przy użyciu kształtów `matplotlib.patches` i wyświetla go w Streamlit.")

# Ustawienia rysunku
fig, ax = plt.subplots(figsize=(6, 8))
ax.set_aspect("equal")
ax.axis("off") # Ukrycie osi

# KORPUS MIKOŁAJA
# --------------------
# Tułów
body = Rectangle((-1.2, -1.0), 2.4, 2.2, color="red")
ax.add_patch(body)
# Kołnierz (biały pasek przy szyi)
collar = Rectangle((-1.2, 1.0), 2.4, 0.2, color="white")
ax.add_patch(collar)
# Pasek
belt = Rectangle((-1.2, 0.0), 2.4, 0.2, color="black")
ax.add_patch(belt)

# Klamra paska
buckle = Rectangle((-0.3, 0.02), 0.6, 0.16, edgecolor="yellow", facecolor="none", linewidth=2)
ax.add_patch(buckle)

# Guziki
for y in [0.7, 0.4, 0.1]:
    button = Circle((0, y), 0.05, color="black")
    ax.add_patch(button)

# NOGI I BUTY
# --------------------
# Nogi
left_leg = Rectangle((-0.7, -1.5), 0.6, 0.5, color="red")
right_leg = Rectangle((0.1, -1.5), 0.6, 0.5, color="red")
ax.add_patch(left_leg)
ax.add_patch(right_leg)

# Buty
left_boot = Rectangle((-0.8, -1.8), 0.8, 0.3, color="black")
right_boot = Rectangle((0.0, -1.8), 0.8, 0.3, color="black")
ax.add_patch(left_boot)
ax.add_patch(right_boot)

# --------------------
# RĘCE
# --------------------
# Ręce (proste prostokąty)
# Użyto transformacji, aby obrócić prostokąty wokół ich lewego dolnego rogu
from matplotlib.transforms import Affine2D

# Lewa ręka
t_left = Affine2D().rotate_deg_around(-1.8, 0.5, 10) + ax.transData
left_arm = Rectangle((-1.8, 0.5), 0.6, 1.0, color="red", transform=t_left)
ax.add_patch(left_arm)

# Prawa ręka
t_right = Affine2D().rotate_deg_around(1.2, 0.5, -10) + ax.transData
right_arm = Rectangle((1.2, 0.5), 0.6, 1.0, color="red", transform=t_right)
ax.add_patch(right_arm)

# Rękawiczki
left_glove = Circle((-1.7, 0.4), 0.25, color="brown")
right_glove = Circle((1.7, 0.4), 0.25, color="brown")
ax.add_patch(left_glove)
ax.add_patch(right_glove)

# --------------------
# GŁOWA
# --------------------
# Głowa
head = Circle((0, 1.6), 0.6, color="#ffddb3")  # jasny kolor skóry
ax.add_patch(head)

# Broda
beard = Ellipse((0, 1.3), 1.0, 0.9, color="white")
ax.add_patch(beard)

# Wąsy
moustache_left = Ellipse((-0.15, 1.45), 0.5, 0.2, angle=15, color="white")
moustache_right = Ellipse((0.15, 1.45), 0.5, 0.2, angle=-15, color="white")
ax.add_patch(moustache_left)
ax.add_patch(moustache_right)

# Nos
nose = Circle((0, 1.5), 0.08, color="#e0a070")
ax.add_patch(nose)

# Oczy
left_eye = Circle((-0.2, 1.7), 0.06, color="white")
right_eye = Circle((0.2, 1.7), 0.06, color="white")
left_pupil = Circle((-0.2, 1.7), 0.03, color="black")
right_pupil = Circle((0.2, 1.7), 0.03, color="black")
ax.add_patch(left_eye)
ax.add_patch(right_eye)
ax.add_patch(left_pupil)
ax.add_patch(right_pupil)

# Uśmiech (prosta linia)
ax.plot([-0.2, 0, 0.2], [1.32, 1.28, 1.32], color="black", linewidth=2)

# CZAPKA
# --------------------
# Czerwona część czapki
hat = Polygon([(-0.8, 1.9), (0.8, 1.9), (0, 2.6)], closed=True, color="red")
ax.add_patch(hat)

# Biały pasek czapki
hat_band = Rectangle((-0.8, 1.8), 1.6, 0.15, color="white")
ax.add_patch(hat_band)

# Pompom
pompom = Circle((0, 2.65), 0.15, color="white")
ax.add_patch(pompom)

# --------------------
# TŁO / PREZENTY (opcjonalne)
# --------------------
# Prosty prezent
gift_box = Rectangle((1.6, -0.6), 0.6, 0.6, color="green")
gift_ribbon_vertical = Rectangle((1.86, -0.6), 0.08, 0.6, color="yellow")
gift_ribbon_horizontal = Rectangle((1.6, -0.32), 0.6, 0.08, color="yellow")
ax.add_patch(gift_box)
ax.add_patch(gift_ribbon_vertical)
ax.add_patch(gift_ribbon_horizontal)

# Zakres osi, żeby wszystko było widać
ax.set_xlim(-2.2, 2.4)
ax.set_ylim(-2.0, 3.0)

# Wyświetlenie figury w Streamlit
st.pyplot(fig)